apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: crossplane-fn-cluster-addons
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: crossplane-fn-cluster-addons
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        clusterRef: sample-customer
